services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres13:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0.15-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -lc "bundle check || bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - rails_tmp:/rails/tmp
      - rails_log:/rails/log
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "1"
      RAILS_MAX_THREADS: "5"
      DATABASE_URL: postgres://postgres:password@db:5432/store_development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  test:
    build: .
    command: bash -lc "bundle check || bundle install && bundle exec rails db:prepare RAILS_ENV=test && bundle exec rspec"
    volumes:
      - .:/rails
      - rails_tmp:/rails/tmp
      - rails_log:/rails/log
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db:5432/store_test
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres13:
  redis_data:
  bundle_cache:
  rails_tmp:
  rails_log:
